### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by plasmoske** [mohrt/oneblock-server-php#1]
Demo doesn't seem to work. Followed instructions on readme but to no luck :(

Thing I noticed was QR doesn't show up on demo

**Comment by mohrt** [comment]
Fixed, there was a missing index.php file under /api/ and a missing fonts folder.

**Comment by mohrt** [comment]
The demo is fixed, give it another download.

**Comment by plasmoske** [comment]
Thanks man. Will give it another go later later today.

:-)
